platform :ios, '16.2'
workspace 'iosApp'
use_frameworks! :linkage => :static

target 'iosApp' do

  pod 'GoogleMLKit/BarcodeScanning'
  pod 'GoogleMLKit/FaceDetection'
  pod 'GoogleMLKit/TextRecognition'
  pod 'GoogleMLKit/PoseDetection'

end
